"""empty message

Revision ID: 07e69ed6ef69
Revises: 5ecd84c07ed6
Create Date: 2022-09-22 20:32:42.444902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e69ed6ef69'
down_revision = '5ecd84c07ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('vin_code', sa.String(length=17), nullable=True),
    sa.Column('brand', sa.String(length=15), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_brand'), 'car', ['brand'], unique=False)
    op.create_index(op.f('ix_car_name'), 'car', ['name'], unique=False)
    op.create_index(op.f('ix_car_release_date'), 'car', ['release_date'], unique=False)
    op.create_index(op.f('ix_car_vin_code'), 'car', ['vin_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_vin_code'), table_name='car')
    op.drop_index(op.f('ix_car_release_date'), table_name='car')
    op.drop_index(op.f('ix_car_name'), table_name='car')
    op.drop_index(op.f('ix_car_brand'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
