"""client

Revision ID: 5ecd84c07ed6
Revises: 1905a8bfeb33
Create Date: 2022-09-18 23:24:52.814861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecd84c07ed6'
down_revision = '1905a8bfeb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('client_id', sa.Integer(), nullable=False))
    op.drop_column('client', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('client', 'client_id')
    # ### end Alembic commands ###
