"""car

Revision ID: 6d1412f85e6e
Revises: e9b91ca2d772
Create Date: 2022-09-30 00:20:38.761420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1412f85e6e'
down_revision = 'e9b91ca2d772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order', 'area', ['area_id'], ['id'])
    op.create_foreign_key(None, 'order', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    # ### end Alembic commands ###
