"""order

Revision ID: 79fb8ffa3c6b
Revises: 6d1412f85e6e
Create Date: 2022-10-05 19:13:43.345071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fb8ffa3c6b'
down_revision = '6d1412f85e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('car_number', sa.String(length=9), nullable=True),
    sa.Column('employee_name', sa.String(length=128), nullable=True),
    sa.Column('area_name', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_view_area_name'), 'order_view', ['area_name'], unique=False)
    op.create_index(op.f('ix_order_view_car_number'), 'order_view', ['car_number'], unique=False)
    op.create_index(op.f('ix_order_view_client_name'), 'order_view', ['client_name'], unique=False)
    op.create_index(op.f('ix_order_view_date'), 'order_view', ['date'], unique=False)
    op.create_index(op.f('ix_order_view_employee_name'), 'order_view', ['employee_name'], unique=False)
    op.create_index(op.f('ix_order_view_expiration_date'), 'order_view', ['expiration_date'], unique=False)
    op.create_unique_constraint(None, 'order', ['employee_id'])
    op.create_foreign_key(None, 'order', 'employee', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'order', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_index(op.f('ix_order_view_expiration_date'), table_name='order_view')
    op.drop_index(op.f('ix_order_view_employee_name'), table_name='order_view')
    op.drop_index(op.f('ix_order_view_date'), table_name='order_view')
    op.drop_index(op.f('ix_order_view_client_name'), table_name='order_view')
    op.drop_index(op.f('ix_order_view_car_number'), table_name='order_view')
    op.drop_index(op.f('ix_order_view_area_name'), table_name='order_view')
    op.drop_table('order_view')
    # ### end Alembic commands ###
