"""ordering service

Revision ID: ab59c9f8a40e
Revises: 79fb8ffa3c6b
Create Date: 2022-10-06 20:17:08.441079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab59c9f8a40e'
down_revision = '79fb8ffa3c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordering_service_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordering_service_view_price'), 'ordering_service_view', ['price'], unique=False)
    op.create_index(op.f('ix_ordering_service_view_quantity'), 'ordering_service_view', ['quantity'], unique=False)
    op.create_index(op.f('ix_ordering_service_view_service_name'), 'ordering_service_view', ['service_name'], unique=False)
    op.create_table('ordering_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordering_service_price'), 'ordering_service', ['price'], unique=False)
    op.create_index(op.f('ix_ordering_service_quantity'), 'ordering_service', ['quantity'], unique=False)
    op.create_foreign_key(None, 'order', 'area', ['area_id'], ['id'])
    op.create_foreign_key(None, 'order', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_ordering_service_quantity'), table_name='ordering_service')
    op.drop_index(op.f('ix_ordering_service_price'), table_name='ordering_service')
    op.drop_table('ordering_service')
    op.drop_index(op.f('ix_ordering_service_view_service_name'), table_name='ordering_service_view')
    op.drop_index(op.f('ix_ordering_service_view_quantity'), table_name='ordering_service_view')
    op.drop_index(op.f('ix_ordering_service_view_price'), table_name='ordering_service_view')
    op.drop_table('ordering_service_view')
    # ### end Alembic commands ###
