"""employee

Revision ID: e9b91ca2d772
Revises: 5ca582c0e49a
Create Date: 2022-09-30 00:19:25.618662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b91ca2d772'
down_revision = '5ca582c0e49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('telephone', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_employee_telephone'), 'employee', ['telephone'], unique=True)
    op.create_foreign_key(None, 'order', 'employee', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'order', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_employee_telephone'), table_name='employee')
    op.drop_column('employee', 'telephone')
    # ### end Alembic commands ###
