"""order

Revision ID: ea1adfecabab
Revises: 890d66f820f7
Create Date: 2022-09-27 02:09:07.707933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1adfecabab'
down_revision = '890d66f820f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_area_status', table_name='area')
    op.drop_column('area', 'status')
    op.add_column('order', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'employee', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'order', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'area_id')
    op.drop_column('order', 'employee_id')
    op.add_column('area', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_area_status', 'area', ['status'], unique=False)
    # ### end Alembic commands ###
